/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './../../../packages/plugins/src/home/studio-routes/settings'
import { Route as ProjectsRouteImport } from './../../../packages/plugins/src/home/studio-routes/projects'
import { Route as ActivityRouteImport } from './../../../packages/plugins/src/home/studio-routes/activity'
import { Route as IndexRouteImport } from './../../../packages/plugins/src/home/studio-routes/index'
import { Route as ProjectsDotindexRouteImport } from './../../../packages/plugins/src/home/studio-routes/projects.index'
import { Route as PostsIndexRouteImport } from './../../../packages/plugins/src/posts/studio-routes/index'
import { Route as AuthIndexRouteImport } from './../../../packages/plugins/src/auth/studio-routes/index'
import { Route as ProjectsDotprojectIdRouteImport } from './../../../packages/plugins/src/home/studio-routes/projects.$projectId'
import { Route as PostsNewRouteImport } from './../../../packages/plugins/src/posts/studio-routes/new'
import { Route as AuthLoginRouteImport } from './../../../packages/plugins/src/auth/studio-routes/login'
import { Route as AuthDeniedRouteImport } from './../../../packages/plugins/src/auth/studio-routes/denied'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDotindexRoute = ProjectsDotindexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDotprojectIdRoute = ProjectsDotprojectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeniedRoute = AuthDeniedRouteImport.update({
  id: '/auth/denied',
  path: '/auth/denied',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/login': typeof AuthLoginRoute
  '/posts/new': typeof PostsNewRoute
  '/projects/$projectId': typeof ProjectsDotprojectIdRoute
  '/auth/': typeof AuthIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsDotindexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/login': typeof AuthLoginRoute
  '/posts/new': typeof PostsNewRoute
  '/projects/$projectId': typeof ProjectsDotprojectIdRoute
  '/auth': typeof AuthIndexRoute
  '/posts': typeof PostsIndexRoute
  '/projects': typeof ProjectsDotindexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/login': typeof AuthLoginRoute
  '/posts/new': typeof PostsNewRoute
  '/projects/$projectId': typeof ProjectsDotprojectIdRoute
  '/auth/': typeof AuthIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsDotindexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/projects'
    | '/settings'
    | '/auth/denied'
    | '/auth/login'
    | '/posts/new'
    | '/projects/$projectId'
    | '/auth/'
    | '/posts/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/settings'
    | '/auth/denied'
    | '/auth/login'
    | '/posts/new'
    | '/projects/$projectId'
    | '/auth'
    | '/posts'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/projects'
    | '/settings'
    | '/auth/denied'
    | '/auth/login'
    | '/posts/new'
    | '/projects/$projectId'
    | '/auth/'
    | '/posts/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthDeniedRoute: typeof AuthDeniedRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PostsNewRoute: typeof PostsNewRoute
  AuthIndexRoute: typeof AuthIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsDotindexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsDotprojectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/denied': {
      id: '/auth/denied'
      path: '/auth/denied'
      fullPath: '/auth/denied'
      preLoaderRoute: typeof AuthDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsDotprojectIdRoute: typeof ProjectsDotprojectIdRoute
  ProjectsDotindexRoute: typeof ProjectsDotindexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsDotprojectIdRoute: ProjectsDotprojectIdRoute,
  ProjectsDotindexRoute: ProjectsDotindexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthDeniedRoute: AuthDeniedRoute,
  AuthLoginRoute: AuthLoginRoute,
  PostsNewRoute: PostsNewRoute,
  AuthIndexRoute: AuthIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { createStart } from '@tanstack/solid-start'

declare module '@tanstack/solid-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}

declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>
  }
}
